# Generated by Django 6.0 on 2026-01-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_ocrmetadata_content_type_alter_invoice_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="receipt_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
