# Generated by Django 6.0 on 2026-01-07 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_receipt_receipt_number"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrmetadata",
            name="object_id",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ocrmetadata",
            name="content_type",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ocr_metadata",
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
    ]
