# Generated by Django 6.0 on 2026-01-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_ocrmetadata_object_id_alter_ocrmetadata_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrmetadata",
            name="processed_image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
