# Generated by Django 6.0 on 2026-01-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_invoice_address_invoice_confidence_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="is_reviewed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="receipt",
            name="is_reviewed",
            field=models.BooleanField(default=False),
        ),
    ]
