# Generated by Django 6.0 on 2026-01-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_invoice_is_reviewed_receipt_is_reviewed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ocrmetadata",
            name="processed_image",
        ),
        migrations.AddField(
            model_name="invoice",
            name="processed_image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="processed_image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
